DROP TABLE Profile CASCADE CONSTRAINTS PURGE;
DROP TABLE Follow CASCADE CONSTRAINTS PURGE;
DROP TABLE Item CASCADE CONSTRAINTS PURGE;
DROP TABLE Paying_Account CASCADE CONSTRAINTS PURGE;
DROP TABLE Buy_Item CASCADE CONSTRAINTS PURGE;
DROP TABLE Commentary CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE seq_1;
DROP TABLE Add_Comment CASCADE CONSTRAINTS PURGE;
DROP TABLE Moderator CASCADE CONSTRAINTS PURGE;
DROP TABLE Moderate CASCADE CONSTRAINTS PURGE;
DROP VIEW v1;
DROP VIEW v2;
DROP PROCEDURE p_delete_item;

